### ISSUE TITLE
Remove dependency on ActiveRecord / ActiveSupport

### ISSUE THREAD

**Issue by mxriverlynn** [fetchapp/fetchapp-api-ruby#2]
I'm not using ActiveRecord or Rails for that matter. I'm using Sinatra and writing up a very simple system that will use the API.

When I load IRB and try to run code, I get errors looking for the `blank?` method - which is part of ActiveRecord / ActiveSupport.

```
FetchAPI::Order.find(:all)
NoMethodError: undefined method `blank?' for {}:Hash
    from /Users/derickbailey/.rvm/gems/ruby-1.9.2-p290@watchmecode/gems/fetchapi-ruby-1.2/lib/fetchapi/base.rb:19:in `find'
    from /Users/derickbailey/.rvm/gems/ruby-1.9.2-p290@watchmecode/gems/fetchapi-ruby-1.2/lib/fetchapi/order.rb:39:in `find'
    from (irb):8
    from /Users/derickbailey/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
```

**Comment by mikelarkin** [comment]
Good call.  Feel free to fork and send a pull request!

**Comment by mikelarkin** [comment]
Sorry for the extreme delay in fixing this.  As of 1.2.4 this is fixed!
