### ISSUE TITLE
Price attribute?

### ISSUE THREAD

**Issue by justinmc28** [fetchapp/fetchapp-api-ruby#8]
I'm using this:

```
 :order_items => [{:sku => 'BPWYWCC2013', :price => "$#{self.amount_in_cents.to_f / 100}"}]
```

But it doesn't seem to work. Do you have to specify float? How do you add the type, if so?

**Comment by mikelarkin** [comment]
Hmm, we'll take a look.  Likely it's on our end, your syntax looks correct.

**Comment by mikelarkin** [comment]
Ah, I see the issue.  You are passing the number in as a string with currency, like "$10.00", but the value needs to be an actual number, not a string.  The currency is set at the order level. 

So, you need 

<pre>:order_items => [{:sku => 'BPWYWCC2013', :price => self.amount_in_cents.to_f / 100}]</pre>

**Comment by justinmc28** [comment]
Sorry, that's a typo on my end when I was retyping I copies and pasted from another section -- the actual code using to send to Fetch has since been removed. 

But I remember trying passing in just random integers that , too -- like say 10.0 -- instead of pulling values out of the database that wouldn't be passed as a string would it? I'll try it again to see if that makes a difference, but as I recally nothign seemed to work.

**Comment by mikelarkin** [comment]
Hmm, that is strange.  If you want to attach another snippet I'll take a look, but the one I pasted above worked for me.
